name: Recent activity charts
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.habits.charts.svg
  token: ${{ secrets.METRICS_TOKEN }}
  base: ""
  plugin_habits: yes
  plugin_habits_facts: no
  plugin_habits_charts: yes
  config_timezone: America/Tijuana
